const mongoose=require('mongoose');
const articleSchema=mongoose.Schema({
    title:{
        type:String,
        minlength:1,
        maxlength:[60,'标题过长'],
        required:[true,'请填写文章标题']
    },
    author:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'User',
    },
    publishDate:{
        type:Date,
        default:Date.now
    },
    cover:{
        type:String,
        default:null
    },
    content:{
        type:String
    },
    class:{
        type:String,
        required:[true,'请选择合适栏目']
    },
    keywords:{
        type:String,
        required:[true,'请选择文章关键字']
    },
    describe:{
        type:String,
        required:[true,'描述必须有']
    },
    hate:{
        type:Number,
        default:1
    },
    love:{
        type:Number,
        default:1
    },
    original:{
        type:Boolean,
        default:false
    },
    notice:{
        type:Boolean,
        default:false
    },
    verify:{
        type:Boolean,
        default:false
    },
    isTop:{
        type:Boolean,
        default:false
    }
});
//分享集合
const shareSchema=mongoose.Schema({
    path:{
        type:String
    },
    isTop:{
        type:Boolean,
        default:false
    }
});
//友链集合
const friendSchema=mongoose.Schema({
    keywords:{
        type:String,
        required:true
    },
    path:{
        type:String,
        required:true
    },
    describe:{
        type:String,
        default:null
    }
});
const Friend=mongoose.model('Friend',friendSchema);
const Share=mongoose.model('Share',shareSchema);
const Article=mongoose.model('Article',articleSchema);
module.exports={
    Article,
    Share,
    Friend
}